// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ParkARContext))]
    [Migration("20251013134240_FixEstadoReservaEnum")]
    partial class FixEstadoReservaEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("HorarioApertura")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HorarioCierre")
                        .HasColumnType("time(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioHora")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cuit = "30-12345678-9",
                            Direccion = "Av. Siempre Viva 123",
                            Email = "contacto@parkar.com",
                            HorarioApertura = new TimeSpan(0, 8, 0, 0, 0),
                            HorarioCierre = new TimeSpan(0, 22, 0, 0, 0),
                            IsDeleted = false,
                            NombreEmpresa = "ParkAR",
                            PrecioHora = 150.00m,
                            Telefono = "341-555-1234"
                        });
                });

            modelBuilder.Entity("Service.Models.Lugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lugares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Numero = 101
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Numero = 102
                        });
                });

            modelBuilder.Entity("Service.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Concepto")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Metodo")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int?>("SuscripcionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.HasIndex("SuscripcionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Concepto = 1,
                            Fecha = new DateTime(2025, 8, 25, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Metodo = 1,
                            Monto = 600.00m,
                            ReservaId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Concepto = 0,
                            Fecha = new DateTime(2025, 8, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Metodo = 2,
                            Monto = 5000.00m,
                            SuscripcionId = 1,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("Service.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int?>("Duracion")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso ilimitado por un mes",
                            Duracion = 30,
                            IsDeleted = false,
                            Nombre = "Plan Mensual",
                            Precio = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Pago por cada hora de uso",
                            IsDeleted = false,
                            Nombre = "Plan por Hora",
                            Precio = 200m
                        });
                });

            modelBuilder.Entity("Service.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoReserva")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LugarId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LugarId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoReserva = 1,
                            FechaFin = new DateTime(2025, 8, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 8, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LugarId = 1,
                            UsuarioId = 1,
                            VehiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            EstadoReserva = 0,
                            FechaFin = new DateTime(2025, 8, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 8, 29, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LugarId = 2,
                            UsuarioId = 1,
                            VehiculoId = 2
                        });
                });

            modelBuilder.Entity("Service.Models.Suscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Suscripciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 1,
                            FechaFin = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PlanId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = 2,
                            FechaFin = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            PlanId = 2,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan@example.com",
                            IsDeleted = false,
                            Nombre = "Juan Pérez",
                            Password = "hashed123",
                            TipoUsuario = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin@example.com",
                            IsDeleted = false,
                            Nombre = "Admin Root",
                            Password = "hashed456",
                            TipoUsuario = 1
                        });
                });

            modelBuilder.Entity("Service.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Patente = "ABC123",
                            TipoVehiculo = 0,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Patente = "XYZ789",
                            TipoVehiculo = 1,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("Service.Models.Pago", b =>
                {
                    b.HasOne("Service.Models.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("ReservaId");

                    b.HasOne("Service.Models.Suscripcion", "Suscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("SuscripcionId");

                    b.HasOne("Service.Models.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Suscripcion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Service.Models.Reserva", b =>
                {
                    b.HasOne("Service.Models.Lugar", "Lugar")
                        .WithMany("Reservas")
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Vehiculo", "Vehiculo")
                        .WithMany("Reservas")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Service.Models.Suscripcion", b =>
                {
                    b.HasOne("Service.Models.Plan", "Plan")
                        .WithMany("Suscripciones")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Models.Usuario", "Usuario")
                        .WithMany("Suscripciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Service.Models.Vehiculo", b =>
                {
                    b.HasOne("Service.Models.Usuario", "Usuario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Service.Models.Lugar", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Service.Models.Plan", b =>
                {
                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("Service.Models.Reserva", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Service.Models.Suscripcion", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Reservas");

                    b.Navigation("Suscripciones");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Service.Models.Vehiculo", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
